import type { DialogueScene } from "../types/DialogueScene";

// сцени та інша іфнормація

export const dialogueData: DialogueScene[] = [
  {
    id: "start",
    text: "Це був звичайний вечір та студенти насолоджувались теплим весняним вечором після важких пар.",
    next: "park",
    backgroundImage: "/public/prologue/places/spring-Hog.png",
    canGoBack: false,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "park",
    text: "Ви також вирішили відпочити від важкого студенського життя. З ким хочете провести час?",
    options: [
      {
        text: "Зі своїм другом",
        nextSceneId: "friend-you",
        importantChoice: "Побути з Другом",
      },
      { text: "Допомогти Професору", nextSceneId: "professor-you" },
      { text: "Провести час на одинці", nextSceneId: "alone" },
    ],
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-you",
    text: "Привіт Тимо! Як справи? Виглядаєш Дивно.",
    next: "friend",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/hidding-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: false,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend",
    text: "Привіт, все добре. Не звертай увагу... сьогодні був дуже важкий день.",
    next: "friend-you-2",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-you-2",
    text: "Так, ти правий, сьогодні справді був важикий день.",
    next: "friend-2",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-2",
    text: "Пам'ятаєш, сьогодні ми проходили тему про чорну магію?",
    next: "friend-you-3",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-you-3",
    text: "Так, а що?",
    next: "friend-3",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-3",
    text: "Да так, я трохи після уроку ще почитав, а як ти відносишся до чорної магії?",
    next: "friend-you-4",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-you-4",
    text: "Звісно що погано, а чого запитуєш?",
    next: "friend-4",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-4",
    text: "Да так, не важливо.",
    next: "Black",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/sus-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "Black",
    text: "Через деякий час",
    next: "friend-you-5",
    backgroundColor: "black",
    canGoBack: true,
  },
  {
    id: "friend-you-5",
    text: "Так що так.",
    next: "friend-you-6",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "friend-you-6",
    text: "Ти це чув?",
    next: "friend-5",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    music: "/music/rain.mp3",
    canGoBack: true,
  },
  {
    id: "friend-5",
    text: "Так, думаю що це гроза",
    next: "rain-park",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/calm-friend.png",
    backgroundImage: "/public/prologue/places/park.png",
    music: "/music/rain.mp3",
    canGoBack: true,
  },
  {
    id: "rain-park",
    text: "І тут небо почало покриватись густими та темними хмарами. Почався сильний вітер та дощ.",
    next: "Hall",
    personageImage: "/public/prologue/personages/friend-knows.png",
    backgroundImage: "/public/prologue/places/rain-park.png",
    music: "/music/rain.mp3",
    canGoBack: true,
  },
  {
    id: "professor-you",
    text: "Добрий вечір профессоре, вам допомогти?",
    next: "professor",
    personageName: "Ви",
    personageImage: "/public/prologue/personages/professor-with-books.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: false,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "professor",
    text: "Добрий вечір! Так, буду дуже вдячний",
    next: "professor-2",
    personageName: "Профессор",
    personageImage: "/public/prologue/personages/professor-with-books.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "professor-2",
    text: "Ось, тримай. Йди за мною",
    next: "Black-2",
    personageName: "Профессор",
    personageImage: "/public/prologue/personages/professor-with-books.png",
    backgroundImage: "/public/prologue/places/park.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "Black-2",
    text: "Через деякий час",
    next: "professor-3",
    backgroundColor: "black",
    canGoBack: true,
  },
  {
    id: "professor-3",
    text: "Дякую за допомогу, хочу поговорити про твою успішність, ти добрий учень але...",
    next: "rain-hog",
    personageName: "Профессор",
    personageImage: "/public/prologue/personages/professor.png",
    backgroundImage: "/public/prologue/places/hogHall.png",
    canGoBack: true,
    music: "/music/elegant.mp3",
  },
  {
    id: "rain-hog",
    text: "І тут небо почало покривуатись густими та темними хмарами. Почався сильний вітер та дощ та через декілька секунд прозвучав вибух.",
    next: "rain-hog-2",
    personageImage: "/public/prologue/personages/professor.png",
    backgroundImage: "/public/prologue/places/rain-hogHall.png",
    canGoBack: true,
    music: "/music/rain.mp3",
  },
  {
    id: "rain-hog-2",
    text: "Негайно біжи в сховище та попередь усіх кого побашиш! Негайно!",
    next: "Hall",
    personageName: "Профессор",
    personageImage: "/public/prologue/personages/scared-professor.png",
    backgroundImage: "/public/prologue/places/rain-hogHall.png",
    canGoBack: true,
    music: "/music/rain.mp3",
  },
  {
    id: "alone",
    text: "Ви вирішили піти прогулятись на околицях Хогвартсу та погрітись першим теплом весни.",
    next: "Black-3",
    backgroundImage: "/public/prologue/places/Hog-grass.png",
    canGoBack: false,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "Black-3",
    text: "Через деякий час",
    next: "alone-2",
    backgroundColor: "black",
    canGoBack: true,
  },
  {
    id: "alone-2",
    text: "Ви побачили, як небо почало завертатись в густі чорні хмари та через пару секунд почався вітер та дощ. Ви якмога швидше побіжали в Хогвартс, але коли ви вже були на порозі, ви почули вибух.",
    next: "Hall",
    backgroundImage: "/public/prologue/places/Hog-grass-rain.png",
    canGoBack: true,
    music: "/music/rain.mp3",
  },
  {
    id: "Hall",
    text: "Коли ви зайшли в коридор вже лунали вибухи і всі біжали в різні сторони. Ви побачили свого друга, який просто забився в кутку і мага відміника, який не знав куди бігти, ви вирішуєте допомогти одному з них або розвідати ситуацію.",
    options: [
      {
        text: "Помогти сильному магу",
        nextSceneId: "help-mag",
        importantChoice: "Поміг магу",
      },
      {
        text: "Помогти другу",
        nextSceneId: "help-friend",
        importantChoice: "Поміг другу",
      },
      {
        text: "Подивитись що відбувається",
        nextSceneId: "go-for-book",
        importantChoice: "Чорна магія-1",
      },
    ],
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/scared.mp3",
  },
  {
    id: "go-for-book",
    text: "Ви вирішили піти розвідати що відбувається та ви побачили Темних духів, які спускались з неба.",
    next: "go-for-book-2",
    backgroundImage: "/public/scene-1/places/hall-book.png",
    canGoBack: false,
    music: "/music/rain.mp3",
  },
  {
    id: "go-for-book-2",
    text: "І ви побачили книгу, яку одразу ж взяли і побіжали за усіма.",
    next: "scene-2",
    backgroundImage: "/public/scene-1/places/hall-book.png",
    canGoBack: true,
    music: "/music/rain.mp3",
  },
  {
    id: "help-friend",
    text: "Ви підійшли до свого друга",
    next: "help-friend-2",
    personageImage: "/public/scene-1/personages/scared-friend.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: false,
    music: "/music/scared.mp3",
  },
  {
    id: "help-friend-2",
    text: "Все добре? Йдемо за мною.",
    personageName: "Ви",
    next: "help-friend-3",
    personageImage: "/public/scene-1/personages/scared-friend.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: true,
    music: "/music/scared.mp3",
  },
  {
    id: "help-friend-3",
    text: "Після цих слів ви побіжали разом за толпою",
    next: "scene-2",
    personageImage: "/public/scene-1/personages/scared-friend.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: true,
    music: "/music/scared.mp3",
  },
  {
    id: "help-mag",
    text: "Ви підійшли до відміника і почули, як він щось говорить",
    next: "help-mag-2",
    personageImage: "/public/scene-1/personages/angry-mag.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: false,
    music: "/music/scared.mp3",
  },
  {
    id: "help-mag-2",
    text: "Я відомщу їм!",
    personageName: "Відмінник",
    next: "help-mag-3",
    personageImage: "/public/scene-1/personages/angry-mag.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: true,
    music: "/music/scared.mp3",
  },
  {
    id: "help-mag-3",
    text: "Все добре? Йдемо за мною.",
    personageName: "Ви",
    next: "help-mag-4",
    personageImage: "/public/scene-1/personages/angry-mag.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: true,
    music: "/music/scared.mp3",
  },
  {
    id: "help-mag-4",
    text: "Після цих слів ви побіжали разом за толпою",
    next: "scene-2",
    personageImage: "/public/scene-1/personages/angry-mag.png",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: true,
    music: "/music/scared.mp3",
  },
  {
    id: "scene-2",
    text: "Коли ви добіжали до сховища одразу ж Ректор почав збирати екстрене обговорення",
    next: "scene-2-1",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "scene-2-1",
    text: "Прошу зберігати тишу! Зараз наша ситуація критична, але наші маги захищають Хогвартс усіма своїми силами.",
    personageName: "Ректор",
    next: "scene-2-2",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "scene-2-2",
    text: "Зараз зверстаюсь до всіх студентів, вам забороняється виходити за межі сховища поки ситуація не стане кращою. Також у нас є підозри до деяких учнів, які можуть бути зрадниками, якщо ви знаєте щось можете зараз сказати.",
    personageName: "Ректор",
    options: [
      {
        text: "Здати свого друга бо він був дивним",
        nextSceneId: "friend-suspision",
        importantChoice: "Здати друга",
        condition: (importantChoices) =>
          importantChoices.has("Побути з Другом"),
      },
      {
        text: "Захистити друга",
        nextSceneId: "friend-good",
        importantChoice: "Захистити друга",
      },
      { text: "Промовчати", nextSceneId: "scene-3" },
    ],
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "friend-suspision",
    text: "Пане ректоре хочу вам повідомити, що мій друг Тимо сьогодні себе дуже дивно поводив та питав про темну магію.",
    personageName: "Ви",
    next: "friend-suspision-2",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: false,
    music: "/music/talkings.mp3",
  },
  {
    id: "friend-suspision-2",
    text: "Це не правда!",
    personageName: "Тимо",
    next: "friend-suspision-3",
    personageImage: "/public/scene-2/personages/scared-friend.png",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "friend-suspision-3",
    text: "Дякую за інформацію! Але хтось один з вас бреше, так що будьте обережні.",
    personageName: "Ректор",
    next: "scene-3",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "friend-good",
    text: "Ви дочекались поки нарада закінчиться та підійшли до ректора",
    next: "friend-good-2",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: false,
    music: "/music/talkings.mp3",
  },
  {
    id: "friend-good-2",
    text: "Пане ректоре хочу вам заявити, я можу вам гарнтувати, що мій кращий друг Тимо точно не з них.",
    personageName: "Ви",
    next: "friend-good-3",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "friend-good-3",
    text: "Дякую за інформацію! Але будь обережний бо навіть близькі люди можуть зрадити.",
    personageName: "Ректор",
    next: "scene-3",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-2/places/basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "scene-3",
    text: "Ви знайшли інше місце в сховищі де немає інших та ви почали думати, як та чим ви можете допомогти врятувати Хогвартс.",
    options: [
      {
        text: "Піти в заборонену частину бібліотеки, бо у вас є книга, у якої обірвані головні сторінки",
        nextSceneId: "biblioteque",
        importantChoice: "Чорна магія-2",
        condition: (importantChoices) => importantChoices.has("Чорна магія-1"),
      },
      {
        text: "Вийти з Хогвартсу та розвідати ситуацію",
        nextSceneId: "forest",
        importantChoice: "Піти в ліс",
      },
      { text: "Залишитись і нічого не робити", nextSceneId: "scene-5" },
    ],
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/epic.mp3",
  },
  {
    id: "biblioteque",
    text: "Ви вирішили піти в бібліотеку, щоб знайти іншу частину книги. В одінй з частин в бібліотеці ви побачили дивне світіння.",
    next: "biblioteque-2",
    backgroundImage: "/public/scene-4/places/bibliotheke.png",
    canGoBack: false,
    music: "/music/bibliotheke.mp3",
  },
  {
    id: "biblioteque-2",
    text: "І це була книга під назвою ''Чорна магія та їхні створіння''. Ви взяли книгу та одразу почали її читати.",
    next: "biblioteque-3",
    backgroundImage: "/public/scene-4/places/dark-book.png",
    canGoBack: false,
    music: "/music/bibliotheke.mp3",
  },
  {
    id: "biblioteque-3",
    text: "Зрозумівши що ці створіння, що напали - це 'Бездушні' маги, які були прокляті на багато віків, але коли ви читали ви почули дивні звуки та побіжали назад.",
    next: "scene-5",
    backgroundImage: "/public/scene-4/places/bibliotheke.png",
    canGoBack: false,
    music: "/music/bibliotheke.mp3",
  },
  {
    id: "forest",
    text: "Ви вирішили непомітно піти в ліс. Дорогою ви побачили, як темні сутності літали навколо Хогвартсу і після цього ви побіжали в ліс.",
    next: "forest-1",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: false,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "forest-1",
    text: "Ви так бігли, що аж не помітили, що перед вами стоїть один з темних магів.",
    next: "forest-2",
    personageImage: "/public/scene-4/personages/calm-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "forest-2",
    text: "Він поводив себе мирно, ви не знаєте що робити.",
    options: [
      {
        text: "Поговорити з ним",
        nextSceneId: "talk-dark",
        importantChoice: "Поговорити з темним магом",
      },
      {
        text: "Втікти",
        nextSceneId: "scene-5",
      },
      { text: "Почати сражатись з ним", nextSceneId: "fight-dark" },
    ],
    personageImage: "/public/scene-4/personages/calm-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "talk-dark",
    text: "Привіт?",
    next: "talk-dark-2",
    personageName: "Ви",
    personageImage: "/public/scene-4/personages/calm-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: false,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "talk-dark-2",
    text: "Схоже ти один з студентів? Думаю, так. Тобі краще зі мною не розмовляти, якщо станеться 'те' тоді буде погано...",
    next: "talk-dark-3",
    personageName: "Темний маг",
    personageImage: "/public/scene-4/personages/calm-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "talk-dark-3",
    text: "Що ви маєте на увазі 'те'?",
    next: "talk-dark-4",
    personageName: "Ви",
    personageImage: "/public/scene-4/personages/calm-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "talk-dark-4",
    text: "Нас всіх прокляли! Та в голові нібито є якийсь ричаг, який змушує нас бути агресивними. Ти нас пробач, але ми є такі по натурі. Тобі краще йти... Зачекай!  А приходь завтра в цей час, мені є тобі що розповісти.",
    next: "talk-dark-5",
    personageName: "Темний маг",
    personageImage: "/public/scene-4/personages/calm-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "talk-dark-5",
    text: "І тут Темний маг почав кричати, ви налякались та побіжали назад в Хогвартс до сховища.",
    next: "scene-5",
    personageImage: "/public/scene-4/personages/angry-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: true,
    music: "/music/forest-sound.mp3",
  },
  {
    id: "fight-dark",
    text: "Ви дістали свою палицю так почали боритись з ним, але ви зрозуміли, що самі не зможете його одолати і побіжали назад.",
    next: "scene-5",
    personageImage: "/public/scene-4/personages/angry-dark.png",
    backgroundImage: "/public/scene-4/places/forest.png",
    canGoBack: false,
    music: "/music/fight.mp3",
  },
  {
    id: "scene-5",
    text: "Коли ви відпочивали. Всі почули, як темні маги прорвались в сховище. Хаос знову набув свій маштаб всі біжали в інший корпус в інше сховище. Ви помітили, що ваш друг кудись пропав, але розумієте, що настав ваш час ви повинні щось робити.",
    options: [
      {
        text: "Допомогти іншим",
        nextSceneId: "help-other",
      },
      {
        text: "Бігти в безпечне місце",
        nextSceneId: "scene-6",
      },
      { text: "Атакувати темних магів", nextSceneId: "fight-dark-inside" },
    ],
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/scared.mp3",
  },
  {
    id: "help-other",
    text: "Ви допомогли іншим та побігли за усіма студентами.",
    next: "scene-6",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: false,
    music: "/music/scared.mp3",
  },
  {
    id: "fight-dark-inside",
    text: "Ви хотіли дати бій, але професор вас відштовхнув і наказав біжати.",
    next: "scene-6",
    backgroundImage: "/public/scene-1/places/running.png",
    canGoBack: false,
    music: "/music/scared.mp3",
  },
  {
    id: "scene-6",
    text: "Ви дійшли до нового сховища та там вже йшло обдумання плану дій для опору темним магам. І ви знаєте, що можете дати справжню пораду.",
    options: [
      {
        text: "Сказати що ви були в лісі і потрібно з ними вести переговори.",
        nextSceneId: "diplomatik",
        condition: (importantChoices) =>
          importantChoices.has("Поговорити з темним магом"),
      },
      {
        text: "Напасти пешими",
        nextSceneId: "attack-first",
        importantChoice: "Напасти першими",
        condition: (importantChoices) => importantChoices.has("Піти в ліс"),
      },
      { text: "Залишитись і нічого не робити", nextSceneId: "attack-first-7" },
    ],
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik",
    text: "Пане ректоре! У мене є новина!",
    next: "diplomatik-1",
    personageName: "Ви",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: false,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik-1",
    text: "Так? Підійди до мене!",
    next: "diplomatik-2",
    personageName: "Ректор",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik-2",
    text: "Хочу зізнатись, що я порушив ваше правило та вийшов за межі Хогвартсу, але я маю важливу інформацію.",
    next: "diplomatik-3",
    personageName: "Ви",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik-3",
    text: "І яку?",
    next: "diplomatik-4",
    personageName: "Ректор",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik-4",
    text: "Я бачив одного з них та говрив з ним і він мені сказав, що вони мають прокляття, яке заставляє робити такі погані справи. Можливо з ними потрібно бути більш добрими та зробити переговори, а потім вже можна з них зняти чари?",
    next: "diplomatik-5",
    personageName: "Ви",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik-5",
    text: "Це дуже ризиковано, але спробувати можна.",
    next: "diplomatik-6",
    personageName: "Ректор",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "diplomatik-6",
    text: "Після цієї розмови Ректор об'явив, що будуть переговори з темними магами і наказав всім відпочити до завтрьошнього ранку.",
    next: "good-final-1",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "good-final-1",
    text: "Того ранку ректор вийшов першим до темних магів і почав переговори, згодом ректор покликав усіх на вулицю. Темні маги були згодні, щоб з них зняли прокляття взамін на допомогу в реставрації Хогвартсу. ",
    next: "good-final-2",
    backgroundImage: "/public/good-final-1/places/good-final.jpg",
    canGoBack: true,
    music: "/music/victory.mp3",
  },
  {
    id: "good-final-2",
    text: "І того ж дня всі чарівники допомогли зняти прокляття з темних магів. І це кінець цієї короткої історії!",
    backgroundImage: "/public/good-final-1/places/good-final-2.png",
    canGoBack: true,
    music: "/music/victory.mp3",
  },
  {
    id: "attack-first",
    text: "Пане ректоре! У мене є ідея!",
    next: "attack-first-2",
    personageName: "Ви",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: false,
    music: "/music/talkings.mp3",
  },
  {
    id: "attack-first-2",
    text: "Так? підійди до мене.",
    next: "attack-first-3",
    personageName: "Ректор",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "attack-first-3",
    text: "Ми б могли напасти першими, я знаю приблизно де у них є табір",
    next: "attack-first-4",
    personageName: "Ви",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "attack-first-4",
    text: "І де?",
    next: "attack-first-5",
    personageName: "Ректор",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "attack-first-5",
    text: "Вибачте що не почлухав вас коли ви заборонили виходити, але я знаю що вони знаходяться в лісі",
    next: "attack-first-6",
    personageName: "Ви",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "attack-first-6",
    text: "Це дуже ризиковано, але спробувати можна.",
    next: "attack-first-7",
    personageName: "Ректор",
    personageImage: "/public/scene-2/personages/rector.png",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "attack-first-7",
    text: "Після цієї розмови Ректор об'явив, що будуть битви з темними магами і наказав всім відпочити до завтрьошнього ранього ранку.",
    next: "scene-7",
    backgroundImage: "/public/scene-6/places/new-basement.png",
    canGoBack: true,
    music: "/music/talkings.mp3",
  },
  {
    id: "scene-7",
    text: "Після промови ректора ви пішли відпочивати, але тут з'явився ваш друг.",
    next: "scene-7-1",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/epic.mp3",
  },
  {
    id: "scene-7-1",
    text: "Привіт! Не скучив?",
    next: "scene-7-2",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/sus-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/epic.mp3",
  },
  {
    id: "scene-7-2",
    text: "Тимо? Це ти? Де ти був?",
    personageName: "Ви",
    next: "scene-7-3",
    personageImage: "/public/prologue/personages/sus-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/epic.mp3",
  },
  {
    id: "scene-7-3",
    text: "З темними магами та я прийшов, щоб зізнатись тобі, що я один з них.",
    next: "scene-7-4",
    personageName: "Тимо",
    personageImage: "/public/prologue/personages/sus-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/epic.mp3",
  },
  {
    id: "scene-7-4",
    text: "Ви в шоці та не знаєте що робити.",
    options: [
      { text: "Почати битву з ним.", nextSceneId: "fight-friend" },
      { text: "Пробачити його", nextSceneId: "trust-friend" },
      { text: "Переконати його", nextSceneId: "talk-friend" },
    ],
    personageImage: "/public/prologue/personages/sus-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/epic.mp3",
  },
  {
    id: "talk-friend",
    text: "Як ти міг!? Ти розумієш, що ти винен в тому що заре робиться? Найкраще що ти можеш зробити це перейти на нашу сторону, але наша дружба вже не буде такою якою була.",
    personageName: "Ви",
    next: "talk-friend-2",
    personageImage: "/public/scene-7/personages/angry-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    music: "/music/epic.mp3",
  },
  {
    id: "talk-friend-2",
    text: "Ти думаєш, що я перейду до такої нікчемної команди? Ти сильно помиляєшся. Бувай!",
    personageName: "Тимо",
    next: "talk-friend-3",
    personageImage: "/public/scene-7/personages/angry-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/epic.mp3",
  },
  {
    id: "talk-friend-3",
    text: "Тимо просто утік від вас і більше цієї ночі ви його не бачили.",
    next: "final",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/epic.mp3",
  },
  {
    id: "fight-friend",
    text: "Як ти міг!? Ти зрадив мене, Хогвартс і усіх кого ти знав! Я тобі не дам це продовжувати.",
    personageName: "Ви",
    next: "fight-friend-2",
    personageImage: "/public/scene-7/personages/angry-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    music: "/music/fight.mp3",
  },
  {
    id: "fight-friend-2",
    text: "У вас почалась битва, але після першого програного заклинання Тимо просто втік.",
    next: "final",
    personageImage: "/public/scene-7/personages/angry-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: true,
    music: "/music/fight.mp3",
  },
  {
    id: "trust-friend",
    text: "Як ти міг! Але я пробачу це, бо ти мій друг.",
    personageName: "Ви",
    next: "trust-friend-2",
    personageImage: "/public/prologue/personages/sus-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    music: "/music/epic.mp3",
  },
  {
    id: "trust-friend-2",
    text: "До речі, якщо так не хочеш стати одним з нас?.",
    personageName: "Тимо",
    options: [
      {
        text: "Зрадити Хогвартс",
        nextSceneId: "final",
        importantChoice: "Примкнути до темних",
        condition: (importantChoices) => importantChoices.has("Чорна магія-2"),
      },
      { text: "Не зраджувати", nextSceneId: "good-player" },
    ],
    personageImage: "/public/scene-1/personages/sus-friend.png",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    resetHistory: true,
    music: "/music/epic.mp3",
  },
  {
    id: "good-player",
    text: "Після цих слів Тимо просто утік від вас і більше цієї ночі ви його не бачили.",
    next: "final",
    backgroundImage: "/public/scene-3/places/basement-home.png",
    canGoBack: false,
    music: "/music/epic.mp3",
  },
  {
    id: "neutral-good-ending",
    text: "На ранок найсильніші маги пішли в засаду де виграли більшість боїв.",
    next: "neutral-good-ending-2",
    backgroundImage: "/public/neutral-final/places/forest-dark.png",
    canGoBack: false,
    music: "/music/victory.mp3",
  },
  {
    id: "neutral-good-ending-2",
    text: "Через деякий час Хогвартс забув про 'Бездушних' та почав житти своїм старим життям. І це кінець цієї маленької історії!",
    backgroundImage: "/public/good-final-2/places/good-final.png",
    canGoBack: false,
    music: "/music/victory.mp3",
  },
  {
    id: "neutral-ending",
    text: "На ранок найсильніші маги пішли в засаду де виграли важливі бої.",
    next: "neutral-good-ending-2",
    backgroundImage: "/public/neutral-final/places/forest-dark.png",
    canGoBack: false,
    music: "/music/neutral.mp3",
  },
  {
    id: "neutral-2",
    text: "Через деякий час Хогвартс забув про 'Бездушних', але він залишився трохи зруйнованим та почав житти своїм старим життям. І це кінець цієї маленької історії!",
    backgroundImage: "/public/good-final-2/places/neutral-final.png",
    canGoBack: false,
    music: "/music/neutral.mp3",
  },
  {
    id: "bad-ending",
    text: "Ви вийшли з Хогвартсу зі своїм другом та він відвів вас до темних де вас прийняли.",
    next: "bad-ending-2",
    backgroundImage: "/public/bad-final/result-bad-ending.png",
    canGoBack: false,
    music: "/music/bad.mp3",
  },
  {
    id: "bad-ending-2",
    text: "Через деякий час Хогвартс впав та темні заволоділи ним. Це кінець цієї маленької історії!",
    backgroundImage: "/public/bad-final/bad-ending.png",
    canGoBack: false,
    music: "/music/bad.mp3",
  },
  {
    id: "good-ending",
    text: "На ранок йшли важкі баталії за Хогвартс, але Маги Хогвартсу змогли відбитись.",
    next: "good-ending-2",
    backgroundImage: "/public/bad-final/places/final-bad-fight.png",
    canGoBack: false,
    music: "/music/victory.mp3",
  },
  {
    id: "good-ending-2",
    text: "Через деякий час Хогвартс забув про ці страшні часи та почав жити своїм старим життям. І тут настав кінець цієї історії!",
    backgroundImage: "/public/good-final-2/places/good-final.png",
    canGoBack: false,
    music: "/music/victory.mp3",
  },
  {
    id: "bad-final",
    text: "На ранок Хогвартс впав.",
    next: "bad-final-2",
    backgroundImage: "/bad-final/places/result-bad-ending.png",
    canGoBack: false,
    music: "/music/bad.mp3",
  },
  {
    id: "bad-final-2",
    text: "темні маги захватили Хогвартс і не збираються зупинятись. Ось тут кінець цієї малої історії!",
    backgroundImage: "/bad-final/places/bad-ending-2.jpg",
    canGoBack: false,
    music: "/music/bad.mp3",
  },
];
